/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ResultLazyImport = createFileRoute('/result')()
const CaptureLazyImport = createFileRoute('/capture')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ResultLazyRoute = ResultLazyImport.update({
  path: '/result',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/result.lazy').then((d) => d.Route))

const CaptureLazyRoute = CaptureLazyImport.update({
  path: '/capture',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/capture.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureLazyImport
      parentRoute: typeof rootRoute
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CaptureLazyRoute,
  ResultLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/capture",
        "/result"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/capture": {
      "filePath": "capture.lazy.tsx"
    },
    "/result": {
      "filePath": "result.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
