/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultImport } from './routes/result'
import { Route as CaptureImport } from './routes/capture'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ResultRoute = ResultImport.update({
  path: '/result',
  getParentRoute: () => rootRoute,
} as any)

const CaptureRoute = CaptureImport.update({
  path: '/capture',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureImport
      parentRoute: typeof rootRoute
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CaptureRoute,
  ResultRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/capture",
        "/result"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/capture": {
      "filePath": "capture.tsx"
    },
    "/result": {
      "filePath": "result.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
